# Generated by Django 5.0.6 on 2024-07-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_carforrent_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carforrent',
            old_name='outsite_price',
            new_name='outside_price',
        ),
    ]
