# Generated by Django 5.0.6 on 2024-07-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_rename_outsite_price_carforrent_outside_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
