# Generated by Django 5.0.6 on 2024-07-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredcarforrent',
            old_name='outsite_price',
            new_name='outside_price',
        ),
    ]
