# Generated by Django 5.0.6 on 2024-07-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_alter_carforrent_accra_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carforrent',
            name='accra_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='car_model',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='color',
            field=models.CharField(blank=True, default='Black', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_for_rent'),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='outside_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='featuredcarforrent',
            name='accra_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='featuredcarforrent',
            name='car_model',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcarforrent',
            name='color',
            field=models.CharField(blank=True, default='Black', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcarforrent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcarforrent',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcarforrent',
            name='outside_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='needadriver',
            name='pick_up_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
