# Generated by Django 5.0.6 on 2024-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_email_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pick_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
