# Generated by Django 5.0.6 on 2024-07-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_drop_off_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_off_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pick_up_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pick_up_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
