# Generated by Django 5.0.6 on 2024-07-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_drop_off_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
