# Generated by Django 5.0.6 on 2024-07-05 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_date_added'),
        ('rental', '0008_rename_outsite_price_featuredcarforrent_outside_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('drop_off_location', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('pick_up_date', models.CharField(blank=True, max_length=20, null=True)),
                ('drop_off_date', models.CharField(blank=True, max_length=20, null=True)),
                ('pick_up_time', models.CharField(max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.featuredcarforrent')),
            ],
            options={
                'verbose_name_plural': 'Featured Bookings',
                'ordering': ['-date_added'],
            },
        ),
    ]
